contentdil = "content"
publishdir = "public"
baseurl = "https://supermil.ch/"
theme = "hugo-nuo"
title = "Manu Wallner"
languageCode = "en-us"
enableRobotsTXT = true

# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-86164156-1"

# Define how many posts should appear on a site
paginate = 5

# Copyright of your post
copyright = "© 2017 Manu Wallner"

[params]
	author = "Manu Wallner"
	avatar = "/images/headshot.jpg"
	subtitle = "Hi, I'm Manu! I'm a software engineer mostly working on mobile apps"
	description = "This is my personal website"

	# Format dates with Go's time formatting
	date_format = "2016-10-21"

	# The icons will be shown if you enter your username
	twitter = "acrooow"
	github = "milch"
	facebook = "apfel"
	linkedin = "https://linkedin.com/in/milch"

# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 5

[[menu.main]]
	name = "GitHub"
	weight = 20
	identifier = "works"
	url = "https://github.com/milch"
