contentdil = "content"
publishdir = "public"
baseurl = "https://supermil.ch/"
theme = "strata"
title = "Manu Wallner"
languageCode = "en-us"

# Enable Google Analytics by inserting your tracking code
# googleAnalytics = ""

# Define how many posts should appear on a site
paginate = 5

[params]
	name = "Manu Wallner"
	description = "This is my personal website"

	# Format dates with Go's time formatting
	date_format = "2016-10-21"

	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "headshot.jpg"

		# Use Markdown to format the string. This works nearly all over the theme
		bio = "\
        **I'm Manu!** \
        I'm a full stack engineer working on mobile apps. \
        I'm also currently studying Engineering Physics. <br> \
        🚀 \
        "

		# The icons will be shown if you enter your username
		twitter = "acrooow"
		github = "milch"
		facebook = "apfel"
		linkedin = "https://linkedin.com/in/milch"

		copyright = [
            "⚡️",
			"&copy; Manu Wallner",
			"Design: [HTML5 UP](//html5up.net)"
		]


	[params.about]
		hide  = false
		title = "About Me"
        content = "\
<h3>Company</h3> <br> \
In 2013, I founded the company [XForge Software Development](//xforge.at). We build complete, native mobile solutions for our customers. Being in a small, three-person team, I learned a lot about working very efficiently - and not being afraid to jump into a project head first. <br> \
<br> \
<h3>Fastlane</h3> <br> \
I am one of the core contributors of the popular [fastlane](https://github.com/fastlane/fastlane) project. Fastlane is used by thousands of developers all over the world and helped save countless wasted developer hours. <br>\
<br> \
<h3>❤️ Open Source</h3> <br> \
This page, all of it's contents, the scripts used to create the whole setup on AWS and the deployment scripts are all [available on GitHub](https://github.com/milch/supermil.ch). <br>\
<br> \
<h3>Recruiters</h3> <br> \
If you are interested in hiring me, you can [contact me](#contact-form) or take a look at my [résumé](pdf/Resume-2016.pdf).\
"

    #TODO: Actually fill in my projects
	[params.portfolio]
		hide  = true 
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "The best way to get in touch with me is this contact form."

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "contact@supermil.ch"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "About"
	url  = "/"
	weight = 5

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10
