version: 2
jobs:
  build:
    branches:
        only:
          - master
    docker:
      - image: circleci/ruby:2
    steps:
      - checkout
      - restore_cache:
          keys:
            - website-cache-{{ .Revision }}
            - website-cache
      - restore_cache:
          keys:
            - deps-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - deps-cache
      - run:
          name: Install dependencies
          command: |
            cd ~

            sudo apt-get update --quiet && sudo apt-get install --assume-yes --quiet python-dev jq
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            ./awscli-bundle/install -b ~/bin/aws
            echo 'export PATH=~/bin:$PATH' >> $BASH_ENV

            curl -L -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.30.2/hugo_0.30.2_Linux-64bit.deb
            sudo dpkg -i hugo.deb

            cd -

            bash .circleci/install_terraform.sh

            gem install bundler
            bundle install --path vendor/bundle
      - save_cache:
          key: deps-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
          - vendor/bundle
          - /var/cache/apt/archives
          - ~/awscli-bundle
      - run:
          name: Initialize Terraform
          command: cd infrastructure && terraform init 
      - run:
          name: Rebuild and upload the site
          command: bundle exec fastlane publish_site
      - save_cache:
          key: website-cache-{{ .Revision }}
          paths: 
            - public/
            - infrastructure/letsencrypt/
